// ============================================================================
// Stimulus Controller: Theme Toggle
// ============================================================================
//
// LEARNING NOTES:
//
// This controller handles dark/light theme switching.
// It demonstrates:
// - Stimulus actions (data-action="click->theme#toggle")
// - LocalStorage for persistence
// - DOM manipulation in Stimulus
//
// HOW STIMULUS CONNECTS TO HTML:
// ------------------------------
// Stimulus uses a convention-based connection system:
//
// 1. CONTROLLER DEFINITION → FILENAME
//    This file is theme_controller.js
//    Therefore, the controller identifier is "theme"
//    (Filename minus _controller.js suffix)
//
// 2. HTML CONNECTION → data-controller
//    In the HTML/Slim: data-controller="theme"
//    This tells Stimulus: "Activate the theme controller on this element"
//
// 3. ACTION CONNECTION → data-action
//    In the HTML: data-action="click->theme#toggle"
//    Format: event->controller#method
//    This says: "On click, call the toggle() method on the theme controller"
//
// 4. TARGET CONNECTION → data-[controller]-target
//    In the HTML: data-theme-target="icon"
//    In the controller: static targets = ["icon"]
//    This gives you: this.iconTarget (the element) and this.hasIconTarget (boolean)
//
// CONTROLLER LIFECYCLE:
// --------------------
// 1. Page loads, Stimulus scans for data-controller attributes
// 2. When found, Stimulus instantiates the controller class
// 3. connect() is called - perfect for setup (like loading saved theme)
// 4. Actions fire when events occur
// 5. disconnect() is called when element leaves DOM (cleanup)
//
// COMPARISON TO NODE.JS/VANILLA JS:
// ---------------------------------
// Express/Vanilla approach:
//   // HTML
//   <button id="theme-toggle"><i id="theme-icon"></i></button>
//   
//   // JavaScript
//   document.addEventListener('DOMContentLoaded', () => {
//     const btn = document.getElementById('theme-toggle')
//     const icon = document.getElementById('theme-icon')
//     
//     btn.addEventListener('click', () => {
//       // toggle logic here
//     })
//   })
//
// Rails/Stimulus approach:
//   // HTML (Slim)
//   button data-controller="theme" data-action="click->theme#toggle"
//     i data-theme-target="icon"
//   
//   // JavaScript (this file)
//   export default class extends Controller {
//     static targets = ["icon"]
//     toggle() { ... }
//   }
//
// KEY DIFFERENCES:
// - Stimulus is declarative: behavior described in HTML
// - No manual querySelector or event listener attachment
// - Controllers automatically connect/disconnect as DOM changes
// - Reusable: same controller can manage multiple elements
//
// ============================================================================

import { Controller } from "@hotwired/stimulus"

// Connects to data-controller="theme"
export default class extends Controller {
  // Targets let us reference specific elements
  // HTML: data-theme-target="icon"
  // JS:   this.iconTarget gives us the element
  // JS:   this.hasIconTarget checks if it exists
  static targets = ["icon"]
  
  // Called when controller connects to the DOM
  // This happens:
  // - On initial page load (if element has data-controller)
  // - When element is dynamically added to DOM (Turbo, AJAX, etc.)
  connect() {
    // Load saved theme preference from browser storage
    const savedTheme = localStorage.getItem('theme') || 'dark'
    this.applyTheme(savedTheme)
    
    console.log('[Theme] Controller connected, theme:', savedTheme)
  }
  
  // Called when controller disconnects from DOM
  // Good for cleanup (removing event listeners, intervals, etc.)
  disconnect() {
    console.log('[Theme] Controller disconnected')
  }
  
  // Toggle between dark and light
  // Called via: data-action="click->theme#toggle"
  // The #toggle means "call the toggle method"
  toggle() {
    const html = document.documentElement
    const currentTheme = html.getAttribute('data-bs-theme')
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark'
    
    this.applyTheme(newTheme)
    localStorage.setItem('theme', newTheme)
    
    console.log('[Theme] Switched to:', newTheme)
  }
  
  // Apply theme to document
  // Helper method - not exposed as an action
  applyTheme(theme) {
    // Bootstrap 5 uses data-bs-theme for theming
    document.documentElement.setAttribute('data-bs-theme', theme)
    
    // Update icon if target exists
    // this.hasIconTarget is automatically generated by Stimulus
    if (this.hasIconTarget) {
      // Change icon class based on theme
      this.iconTarget.className = theme === 'dark' 
        ? 'bi bi-moon-fill'   // Moon icon for dark mode
        : 'bi bi-sun-fill'    // Sun icon for light mode
    }
  }
}
